apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-1-static
spec:
  capacity:
    storage: 500Mi
  accessModes:
  - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /mnt/nfs-vol
    server: k8scp
    readOnly: false
