apiVersion: v1
kind: Pod
metadata:
  name: mypv-test-big-slow
  namespace: default
spec:
  restartPolicy: Never
  volumes:
  - name: vol
    persistentVolumeClaim:
      claimName: myclaim-2-big-slow
  containers:
  - name: pv-test
    image: mjbright/ckad-demo:alpine1
    command: ["/bin/sh", "-c", "while true; do echo $(hostname): $(date) >> /cmount/date.log; sleep 1; done"]
    volumeMounts:
    - name: vol
      mountPath: /cmount
