apiVersion: batch/v1beta1
kind: CronJob
metadata:
  labels:
    app: ckad-demo-cronjob
  name: ckad-demo-cronjob
spec:
  schedule: "* * * * *" # Every minute !!
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: ckad-demo-cronjob
        spec:
          restartPolicy: Never
          containers:
          - image: mjbright/ckad-demo:alpine1
            name: ckad-demo-cronjob
            command: ['/bin/sleep', '7']
