apiVersion: v1
kind: Pod
metadata:
  labels:
    run: pv-demo-2-ed
  name: pv-demo-2-ed
spec:
  volumes:
  - name: ed
    emptyDir: {}

  containers:

  - image: mjbright/ckad-demo:alpine1
    name: pv-demo

    volumeMounts:
    - mountPath: /m1
      name: ed

  - image: mjbright/ckad-demo:alpine1
    name: pv-demo2
    command: ['/bin/sh', '-c', 'while true; do echo $(hostname): $(date) >> /m2/date.log; sleep 1; done']

    volumeMounts:
    - mountPath: /m2
      name: ed


