
# To use this manifest:
# - kubectl create -f pod.yaml
#
# - kubectl exec -it simple-pod -- sh
#   # ls -al /mnt/vol
#   # id
#   # touch /tmp/X   # Note that we can write within container filesystem
#
#   # wget -qO - web
#   # ping web       # OK
#   # grep Cap /proc/176/status
#
#   # exit
#
# - ls -al /mnt/data # Note file ownership on the host node

apiVersion: v1
kind: Pod
metadata:
  labels:
    run: simple-pod
  name:  simple-pod
spec:

  # We will bind the Pod to our only control-plane node,
  # - to simplify the demo (run totally from cp node)
  nodeSelector:
    node-role.kubernetes.io/control-plane: ""

  containers:
  - image: mjbright/k8s-demo:alpine1
    name:  simple-pod

    # Append the current date to a file on the mounted volume
    command: ["/bin/sh", "-c", "while true; do date >> /mnt/vol/pod_date.log; sleep 1; done"]

    volumeMounts:
    - name:      simple-pod
      mountPath: /mnt/vol

  volumes:
  - name: simple-pod
    #emptyDir: {}
    hostPath:
      path: /mnt/data

